/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TodoApp;

import controller.ProjectController;
import java.util.Date;
import java.util.List;
import model.Project;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        ProjectController projectController = new ProjectController();
        
//        projectController.removeById(3);
        Project project = new Project();
        
        project.setName("John project");
        project.setDescription("Description");
        project.setUpdatedAt(new Date());
        projectController.save(project);
        
        List<Project> projects = projectController.getAll();
        System.out.println("Total de projetos " + projects.size());
//        System.out.println(new App().getGreeting());
    }
}
